use crate::UnderlyingInt;

const ALL_EXPS: [i128; 39] = [
    1,
    10_i128.pow(1),
    10_i128.pow(2),
    10_i128.pow(3),
    10_i128.pow(4),
    10_i128.pow(5),
    10_i128.pow(6),
    10_i128.pow(7),
    10_i128.pow(8),
    10_i128.pow(9),
    10_i128.pow(10),
    10_i128.pow(11),
    10_i128.pow(12),
    10_i128.pow(13),
    10_i128.pow(14),
    10_i128.pow(15),
    10_i128.pow(16),
    10_i128.pow(17),
    10_i128.pow(18),
    10_i128.pow(19),
    10_i128.pow(20),
    10_i128.pow(21),
    10_i128.pow(22),
    10_i128.pow(23),
    10_i128.pow(24),
    10_i128.pow(25),
    10_i128.pow(26),
    10_i128.pow(27),
    10_i128.pow(28),
    10_i128.pow(29),
    10_i128.pow(30),
    10_i128.pow(31),
    10_i128.pow(32),
    10_i128.pow(33),
    10_i128.pow(34),
    10_i128.pow(35),
    10_i128.pow(36),
    10_i128.pow(37),
    10_i128.pow(38),
];

// maxmax = pow(2, 121) - 1
// for i in range(1,40):
//     print("%d," % (maxmax // pow(10, i)))
const AVAIL_THRESHOLD: [i128; 37] = [
    265845599156983174580761412056068915,
    26584559915698317458076141205606891,
    2658455991569831745807614120560689,
    265845599156983174580761412056068,
    26584559915698317458076141205606,
    2658455991569831745807614120560,
    265845599156983174580761412056,
    26584559915698317458076141205,
    2658455991569831745807614120,
    265845599156983174580761412,
    26584559915698317458076141,
    2658455991569831745807614,
    265845599156983174580761,
    26584559915698317458076,
    2658455991569831745807,
    265845599156983174580,
    26584559915698317458,
    2658455991569831745,
    265845599156983174,
    26584559915698317,
    2658455991569831,
    265845599156983,
    26584559915698,
    2658455991569,
    265845599156,
    26584559915,
    2658455991,
    265845599,
    26584559,
    2658455,
    265845,
    26584,
    2658,
    265,
    26,
    2,
    0,
];

fn get_exp(i: u8) -> i128 {
    debug_assert!(i <= 36);
    unsafe { *ALL_EXPS.get_unchecked(i as usize) }
}

impl UnderlyingInt for i128 {
    const MAX: Self = Self::MAX;
    const MIN: Self = Self::MIN;
    const ZERO: Self = 0;
    const TEN: Self = 10;
    const BITS: u8 = 128;
    const MATISSA_DIGITS: u8 = 36;
    const SCALE_BITS: u8 = 6;
    const MAX_SCALE: u8 = 36;
    const IS_SIGNED: bool = true;

    fn as_u8(self) -> u8 {
        self as u8
    }
    fn from_u8(n: u8) -> Self {
        n as Self
    }

    fn leading_zeros(self) -> u32 {
        self.leading_zeros()
    }

    fn avail_digits(self) -> u8 {
        let n = self.abs() | 1; // make 0 -> 1
        let bits = n.leading_zeros() - Self::SCALE_BITS as u32 - 1; // 1 for sign
        let digits = bits * 1233 >> 12; // math!
        let ath = unsafe { AVAIL_THRESHOLD.get_unchecked(digits as usize) };
        digits as u8 + (&n <= ath) as u8
    }

    fn mul_with_sum_scale(self, right: Self, sum_scale: u8) -> Option<(Self, u8)> {
        let ua = self.abs();
        let ub = right.abs();

        if ((ua.leading_zeros() + ub.leading_zeros()) as u8) < 128 - Self::SCALE_BITS - 1 {
            let p = self * right;
            if sum_scale <= Self::MAX_SCALE {
                Some((p, sum_scale))
            } else {
                let diff = sum_scale - Self::MAX_SCALE;
                Some((p.div_exp(diff), Self::MAX_SCALE))
            }
        } else {
            let mut more_digits = 0;
            if sum_scale <= Self::MAX_SCALE {
                if more_digits > sum_scale {
                    return None;
                }
            } else {
                more_digits = more_digits.max(sum_scale - Self::MAX_SCALE);
            }
            // self.word2_div_exp(high, low, more_digits);
            todo!()
        }
    }

    // caller must make sure that no overflow
    fn mul_exp(self, iexp: u8) -> Self {
        self * get_exp(iexp)
    }

    #[inline] // TODO good for mac, bad for linux
    fn div_exp(self, iexp: u8) -> Self {
        let exp = get_exp(iexp);
        let n = self.unsigned_abs() + exp as u128 / 2; // no addition overflow. exp is even.
        let q = div_exp_fast_1word(n, iexp as usize) as i128;
        if self >= 0 { q } else { -q }
    }
}

// calculate fast: n / 10.pow(i)
//
// n is 1-word, 128-bit, same with divisor(exp).
//
// Use the algorithm in Granlund & Montgomery's paper:
//   https://gmplib.org/%7Etege/divcnst-pldi94.pdf
// A good tutorial for the algorithm:
//   https://homepage.divms.uiowa.edu/%7Ejones/bcd/divide.html
fn div_exp_fast_1word(n: u128, i: usize) -> u128 {
    // The magics are generated by python code:
    //
    // def gen(d):
    //    l = math.ceil( math.log2(d) )
    //    m = pow(2, 128+l) // d + 1
    //    m = m - pow(2, 128) # make m fit in 128-bit
    //    return (m, l - 1)
    const GM_EXP_MAGICS: [(u128, u32); 39] = [
        (0, 0),
        (0x9999999999999999999999999999999a, 3),
        (0x47ae147ae147ae147ae147ae147ae148, 6),
        (0x0624dd2f1a9fbe76c8b4395810624dd3, 9),
        (0xa36e2eb1c432ca57a786c226809d4952, 13),
        (0x4f8b588e368f08461f9f01b866e43aa8, 16),
        (0x0c6f7a0b5ed8d36b4c7f349385836220, 19),
        (0xad7f29abcaf485787a6520ec08d2369a, 23),
        (0x5798ee2308c39df9fb841a566d74f87b, 26),
        (0x12e0be826d694b2e62d01511f12a6062, 29),
        (0xb7cdfd9d7bdbab7d6ae6881cb5109a37, 33),
        (0x5fd7fe17964955fdef1ed34a2a73ae92, 36),
        (0x19799812dea11197f27f0f6e885c8ba8, 39),
        (0xc25c268497681c2650cb4be40d60df74, 43),
        (0x6849b86a12b9b01ea70909833de71929, 46),
        (0x203af9ee756159b21f3a6e0297ec1421, 49),
        (0xcd2b297d889bc2b6985d7cd0f3135368, 53),
        (0x70ef54646d496892137dfd73f5a90f86, 56),
        (0x2725dd1d243aba0e75fe645cc4873f9f, 59),
        (0xd83c94fb6d2ac34a5663d3c7a0d865cb, 63),
        (0x79ca10c9242235d511e976394d79eb09, 66),
        (0x2e3b40a0e9b4f7dda7edf82dd794bc07, 69),
        (0xe392010175ee5962a6498d1625bac671, 73),
        (0x82db34012b25144eeb6e0a781e2f0528, 76),
        (0x357c299a88ea76a58924d52ce4f26a86, 79),
        (0xef2d0f5da7dd8aa27507bb7b07ea440a, 83),
        (0x8c240c4aecb13bb52a6c95fc0655033b, 86),
        (0x3ce9a36f23c0fc90eebd44c99eaa68fc, 89),
        (0xfb0f6be50601941b17953adc3110a7f9, 93),
        (0x95a5efea6b34767c12ddc8b027408661, 96),
        (0x4484bfeebc29f863424b06f3529a051b, 99),
        (0x039d66589687f9e901d59f290ee19daf, 102),
        (0x9f623d5a8a732974cfbc31db4b0295e5, 106),
        (0x4c4e977ba1f5bac3d9635b15d59bab1d, 109),
        (0x09d8792fb4c495697ab5e277de16227e, 112),
        (0xa95a5b7f87a0ef0f2abc9d8c9689d0c9, 116),
        (0x54484932d2e725a5bbca17a3aba173d4, 119),
        (0x1039d428a8b8eaeafca1ac82efb45caa, 122),
        (0xb38fb9daa78e44ab2dcf7a6b19209443, 126),
    ];

    // SAFETY: caller must make sure i is in range
    let magic = unsafe { GM_EXP_MAGICS.get_unchecked(i) };

    // (n + ((n * m) >> 128)) >> l
    let (high, _) = mul2(n, magic.0);

    // n + high may overflow, so
    // note: magic.1 = l - 1
    (high + ((n - high) >> 1)) >> magic.1
}

// calculate: a * b = (mhigh,mlow)
const fn mul2(a: u128, b: u128) -> (u128, u128) {
    let (ahigh, alow) = (a >> 64, a & u64::MAX as u128);
    let (bhigh, blow) = (b >> 64, b & u64::MAX as u128);

    let (mid, carry1) = (alow * bhigh).overflowing_add(ahigh * blow);
    let (mlow, carry2) = (alow * blow).overflowing_add(mid << 64);
    let mhigh = ahigh * bhigh + (mid >> 64) + ((carry1 as u128) << 64) + carry2 as u128;
    (mhigh, mlow)
}
